@startuml
'https://plantuml.com/sequence-diagram
|||
participant "fluid:Fluid"

->"fluid:Fluid" : addFluid(inputArguments: String)
activate "fluid:Fluid" #FFBBBB

"fluid:Fluid"->"fluid:Fluid" : generateFluidParameters(inputArguments: String)
activate "fluid:Fluid" #DarkSalmon
return
|||
alt invalid fluid description / missing parameters \n/ description has separators
else else
"fluid:Fluid"->"fluid:Fluid" : fluidArray.add(inputArguments: String)
activate "fluid:Fluid" #IndianRed
return
|||
    end
    note left : if block only throws an exception
    |||
    deactivate "fluid:Fluid"
    |||
@enduml