@startuml
'https://plantuml.com/sequence-diagram
participant ":ScheduleTracker"
participant ":ScheduledWorkout"

->":ScheduleTracker" : addScheduledWorkout(inputArguments: String)
activate ":ScheduleTracker" #FFBBBB

":ScheduleTracker"->":ScheduleTracker" : cleanUpScheduleList()
note right: Take note that the method calls \nare NOT comprehensive. \ne.g.some  method calls such as \ngenerating of paramaters are omitted
activate ":ScheduleTracker" #DarkSalmon

loop \tno more overdue workouts\t
    note left : Take note that a workout is "overdue" \nif its scheduled date is before the current date
    ":ScheduleTracker"->":ScheduleTracker" : updateOrDeleteScheduledWorkout(\n\tscheduledWorkout : ScheduleWorkout,\n\tcurrentDate: LocalDate)
    activate ":ScheduleTracker" #IndianRed
    alt \tisRecurringWorkout\t
        ":ScheduleTracker"->":ScheduleTracker" : rescheduleRecurringWorkout(\n\tscheduledWorkout : ScheduleWorkout,\n\tcurrentDate: LocalDate)
        activate ":ScheduleTracker" #LightSalmon
        ":ScheduleTracker"->":ScheduledWorkout" : incrementWorkoutDate(days: long)
        |||
        activate ":ScheduledWorkout"
        return
        return
        |||
    else else
        ":ScheduleTracker"->":ScheduleTracker" : deleteWorkout()
        activate ":ScheduleTracker" #LightSalmon
        ":ScheduleTracker"->":ScheduledWorkout" : scheduledWorkouts.remove(\n\tscheduledWorkout : ScheduleWorkout)
        activate ":ScheduledWorkout"
        destroy ":ScheduledWorkout"
        return
        return
        |||
    end
end

":ScheduleTracker"->":ScheduleTracker" : sortScheduleList()
activate ":ScheduleTracker" #LightSalmon
return

return
return
return

@enduml