@startuml
'https://plantuml.com/sequence-diagram
participant ":ScheduleTracker"

->":ScheduleTracker" : addScheduledWorkout(inputArguments: String)
activate ":ScheduleTracker" #FFBBBB

":ScheduleTracker"->":ScheduleTracker" : generateParameters(inputArguments: String)
activate ":ScheduleTracker" #DarkSalmon
return generatedParameters: String[]

create ":ScheduledWorkout"
":ScheduleTracker"->":ScheduledWorkout" : scheduledWorkouts.add(scheduledWorkout: ScheduledWorkout)
activate ":ScheduledWorkout"
":ScheduledWorkout"-->":ScheduleTracker"
deactivate ":ScheduledWorkout"

":ScheduleTracker"->":ScheduleTracker" : cleanUpScheduleList()

activate ":ScheduleTracker" #DarkSalmon

loop \tno more overdue workouts\t
    note left : Take note that a workout is "overdue" \nif its scheduled date is before the current date
    ":ScheduleTracker"->":ScheduleTracker" : updateOrDeleteScheduledWorkout(\n\tscheduledWorkout: ScheduledWorkout,\n\tcurrentDate: LocalDate)
    activate ":ScheduleTracker" #IndianRed
    alt \tisRecurringWorkout\t
        ":ScheduleTracker"->":ScheduleTracker" : rescheduleRecurringWorkout(\n\tscheduledWorkout: ScheduledWorkout,\n\tcurrentDate: LocalDate)
        activate ":ScheduleTracker" #LightSalmon
        ":ScheduleTracker"->":ScheduledWorkout" : incrementWorkoutDate(days: long)
        |||
        activate ":ScheduledWorkout"
        return
        return
        |||
    else else
        ":ScheduleTracker"->":ScheduleTracker" : deleteWorkout()
        activate ":ScheduleTracker" #LightSalmon
        ":ScheduleTracker"->":ScheduledWorkout" : scheduledWorkouts.remove(\n\tscheduledWorkout: ScheduledWorkout)
        activate ":ScheduledWorkout"
        destroy ":ScheduledWorkout"
        return
        return
        |||
    end
end

":ScheduleTracker"->":ScheduleTracker" : sortScheduleList()
activate ":ScheduleTracker" #LightSalmon
return

return
return
return

@enduml